---
# ansible
templates_path: "templates"

# bind
bind_path: "/etc/bind"
zone_path: "/etc/bind/zone"
bind_logs_path: "/var/log/named"
bind_query_logs_file: "queries.log"

# dns
ttl: "2"
num: "{{ ansible_date_time.date | replace('-', '') }}01"
ref: "3600"
ret: "1800"
exp: "3600"

# prometheus + elasticsearch
prel_root_dir: "/opt/prel"

elasticsearch_img: "elastic/elasticsearch:9.2.3"
logstash_img: "elastic/logstash:9.1.9"
kibana_img: "elastic/kibana:9.1.9"
filebeat_img: "elastic/filebeat:8.19.9"

# vector
vector_path: "/etc/vector"
